model:
  default: deepseek-v4-flash
  provider: deepseek
  base_url: https://api.deepseek.com
agent:
  max_turns: 150
display:
  tool_progress: all
memory:
  provider: openviking
  openviking:
    use_ovcli_config: true
    ovcli_config_path: /root/.openviking/ovcli.conf.zjx
_config_version: 33
session_reset:
  mode: none
gateway:
  platforms:
    slack:
      enabled: false
    whatsapp:
      enabled: false
    webhook:
      enabled: false
    feishu:
      enabled: false
    irc:
      enabled: false
    homeassistant:
      enabled: false
    weixin:
      enabled: false
    sms:
      enabled: false
    yuanbao:
      enabled: false
    discord:
      enabled: false
    bluebubbles:
      enabled: false
    line:
      enabled: false
    signal:
      enabled: false
    teams:
      enabled: false
    raft:
      enabled: false
    email:
      enabled: false
    wecom:
      enabled: false
    whatsapp_cloud:
      enabled: false
    google_chat:
      enabled: false
    telegram:
      enabled: false
    buzz:
      enabled: false
    relay:
      enabled: false
    wecom_callback:
      enabled: false
    dingtalk:
      enabled: false
    mattermost:
      enabled: false
    api_server:
      enabled: true
    photon:
      enabled: false
    ntfy:
      enabled: false
    qqbot:
      enabled: false
    a2a:
      enabled: false
    msgraph_webhook:
      enabled: false
    matrix:
      enabled: false
    simplex:
      enabled: false
  api_server:
    enabled: true
platforms:
  slack:
    enabled: false
  whatsapp:
    enabled: false
  webhook:
    enabled: false
  feishu:
    enabled: false
  irc:
    enabled: false
  homeassistant:
    enabled: false
  weixin:
    enabled: false
  sms:
    enabled: false
  yuanbao:
    enabled: false
  discord:
    enabled: false
  bluebubbles:
    enabled: false
  line:
    enabled: false
  signal:
    enabled: false
  teams:
    enabled: false
  raft:
    enabled: false
  email:
    enabled: false
  wecom:
    enabled: false
  whatsapp_cloud:
    enabled: false
  google_chat:
    enabled: false
  telegram:
    enabled: false
  buzz:
    enabled: false
  relay:
    enabled: false
  wecom_callback:
    enabled: false
  dingtalk:
    enabled: false
  mattermost:
    enabled: false
  api_server:
    enabled: true
  photon:
    enabled: false
  ntfy:
    enabled: false
  qqbot:
    enabled: false
  a2a:
    enabled: false
  msgraph_webhook:
    enabled: false
  matrix:
    enabled: false
  simplex:
    enabled: false
